// The sneaker demo client's catalogue (Northvale Kicks, lib/demo/clients.ts): the models a reseller like them holds,
// with style codes, colourways and size runs as StockX and Picqer write them. A curated list of well-known models
// (Jordan retros, Dunks, Air Max, New Balance, adidas terrace, ASICS, Salomon…), the 2025–2026 releases weighted up;
// no Yeezy. Every number the demo shows about these products (sales, stock, links) is generated by lib/demo/sample.ts.
// Pure data (no I/O, no "@/" imports): node --test can load it.

export type Run = "m" | "j" | "w" | "gs" | "ad" | "nb" | "as" | "sa" | "sl";
/** a side-profile shape for the product drawing (lib/demo/art.ts) */
export type Shape = "low" | "mid" | "high" | "runner" | "slide";

// [US size, EU size] as the marketplaces and Picqer write them; demand peaks around `peak`
export const RUNS: Record<Run, { peak: number; spread: number; sizes: [string, string][] }> = {
  // Nike and Jordan men's (Jordans from US 7)
  m: { peak: 9.75, spread: 1.9, sizes: [["6", "38.5"], ["6.5", "39"], ["7", "40"], ["7.5", "40.5"], ["8", "41"], ["8.5", "42"], ["9", "42.5"], ["9.5", "43"],
    ["10", "44"], ["10.5", "44.5"], ["11", "45"], ["11.5", "45.5"], ["12", "46"], ["12.5", "47"], ["13", "47.5"], ["14", "48.5"]] },
  j: { peak: 9.75, spread: 1.9, sizes: [["7", "40"], ["7.5", "40.5"], ["8", "41"], ["8.5", "42"], ["9", "42.5"], ["9.5", "43"], ["10", "44"], ["10.5", "44.5"],
    ["11", "45"], ["11.5", "45.5"], ["12", "46"], ["12.5", "47"], ["13", "47.5"], ["14", "48.5"]] },
  w: { peak: 7.75, spread: 1.5, sizes: [["5W", "35.5"], ["5.5W", "36"], ["6W", "36.5"], ["6.5W", "37.5"], ["7W", "38"], ["7.5W", "38.5"], ["8W", "39"],
    ["8.5W", "40"], ["9W", "40.5"], ["9.5W", "41"], ["10W", "42"], ["10.5W", "42.5"], ["11W", "43"], ["12W", "44"]] },
  gs: { peak: 5.5, spread: 1.2, sizes: [["3.5Y", "35.5"], ["4Y", "36"], ["4.5Y", "36.5"], ["5Y", "37.5"], ["5.5Y", "38"], ["6Y", "38.5"], ["6.5Y", "39"], ["7Y", "40"]] },
  ad: { peak: 9, spread: 2.3, sizes: [["5.5", "38"], ["6", "38 2/3"], ["6.5", "39 1/3"], ["7", "40"], ["7.5", "40 2/3"], ["8", "41 1/3"], ["8.5", "42"],
    ["9", "42 2/3"], ["9.5", "43 1/3"], ["10", "44"], ["10.5", "44 2/3"], ["11", "45 1/3"], ["11.5", "46"], ["12", "46 2/3"], ["12.5", "47 1/3"], ["13", "48"]] },
  nb: { peak: 9.75, spread: 1.8, sizes: [["7", "40"], ["7.5", "40.5"], ["8", "41.5"], ["8.5", "42"], ["9", "42.5"], ["9.5", "43"], ["10", "44"], ["10.5", "44.5"],
    ["11", "45"], ["11.5", "45.5"], ["12", "46.5"], ["13", "47.5"]] },
  as: { peak: 9.5, spread: 1.8, sizes: [["7", "40"], ["7.5", "40.5"], ["8", "41.5"], ["8.5", "42"], ["9", "42.5"], ["9.5", "43.5"], ["10", "44"], ["10.5", "44.5"],
    ["11", "45"], ["11.5", "46"], ["12", "46.5"], ["12.5", "47"], ["13", "48"]] },
  sa: { peak: 9.5, spread: 1.9, sizes: [["6.5", "39 1/3"], ["7", "40"], ["7.5", "40 2/3"], ["8", "41 1/3"], ["8.5", "42"], ["9", "42 2/3"], ["9.5", "43 1/3"],
    ["10", "44"], ["10.5", "44 2/3"], ["11", "45 1/3"], ["12", "46 2/3"], ["13", "48"]] },
  sl: { peak: 9.5, spread: 2, sizes: [["5", "37.5"], ["6", "38.5"], ["7", "40"], ["8", "41"], ["9", "42.5"], ["10", "44"], ["11", "45"], ["12", "46"], ["13", "47.5"], ["14", "48.5"]] },
};

// [name as StockX writes it, style code, colourway, size run, how well it sells (1–5), release date, resale € (when it
// isn't the usual price for its kind)]
type Row = [name: string, style: string, color: string, run: Run, hype: number, rel: string, eur?: number];

const ROWS: Row[] = [
  // Jordan 1 High
  ["Jordan 1 Retro High OG Chicago Lost and Found", "DZ5485-612", "Varsity Red/Black/Sail", "j", 4, "2022-11-19"],
  ["Jordan 1 Retro High OG Lost and Found (GS)", "FD1437-612", "Varsity Red/Black/Sail", "gs", 3, "2022-11-19"],
  ["Jordan 1 Retro High OG Yellow Ochre", "DZ5485-701", "Yellow Ochre/Black", "j", 2, "2023-08-26"],
  ["Jordan 1 Retro High OG Royal Reimagined", "DZ5485-042", "Black/Royal Blue", "j", 3, "2023-11-04"],
  ["Jordan 1 Retro High OG UNC Toe", "DZ5485-400", "University Blue/Black", "j", 2, "2023-07-29"],
  ["Jordan 1 Retro High OG Spider-Man Across the Spider-Verse", "DV1748-601", "University Red/Black", "j", 2, "2023-05-31"],
  ["Jordan 1 Retro High OG Dark Mocha", "555088-105", "Sail/Dark Mocha", "j", 3, "2020-10-31"],
  ["Jordan 1 Retro High OG Patent Bred", "555088-063", "Black/Varsity Red", "j", 2, "2021-12-11"],
  ["Jordan 1 Retro High OG University Blue", "555088-134", "White/University Blue", "j", 3, "2021-03-06"],
  ["Jordan 1 Retro High OG Taxi", "555088-711", "Taxi/Black", "j", 2, "2022-08-13"],
  ["Jordan 1 Retro High OG Shadow 2.0", "555088-035", "Black/Light Smoke Grey", "j", 2, "2021-05-15"],
  ["Jordan 1 Retro High OG Heritage", "555088-161", "White/University Red", "j", 2, "2022-05-07"],
  ["Jordan 1 Retro High OG Bred Toe", "555088-610", "Gym Red/Black", "j", 2, "2018-02-24"],
  ["Jordan 1 Retro High OG Black Toe Reimagined", "DZ5485-106", "White/Black/Varsity Red", "j", 4, "2025-02-15"],
  ["Jordan 1 Retro High OG Pro Green", "DZ5485-303", "Pro Green/White", "j", 2, "2025-05-10"],
  ["Jordan 1 Retro High OG Shattered Backboard", "DZ5485-008", "Black/Starfish", "j", 3, "2025-09-13"],
  ["Jordan 1 Retro High OG Rare Air", "DZ5485-101", "Sail/Cinnabar/Black", "j", 3, "2026-03-21"],
  ["Jordan 1 Retro High OG Bred Reimagined", "DZ5485-061", "Black/Varsity Red", "j", 5, "2026-06-13"],
  ["Jordan 1 Retro High OG SP Travis Scott Mocha", "CD4487-100", "Sail/Dark Mocha", "j", 2, "2019-05-11", 1150],
  ["Jordan 1 Retro High OG Satin Bred (Women's)", "FD4810-061", "Black/Varsity Red", "w", 2, "2023-08-03"],
  ["Jordan 1 Retro High OG Washed Pink (Women's)", "FD2596-600", "Atmosphere/Soft Pink", "w", 2, "2024-04-13"],
  ["Jordan 1 Retro High OG Black Toe Reimagined (GS)", "FD1437-106", "White/Black/Varsity Red", "gs", 3, "2025-02-15"],
  // Jordan 1 Low
  ["Jordan 1 Retro Low OG SP Travis Scott Reverse Mocha", "DM7866-162", "Sail/Ridgerock", "j", 4, "2022-07-21", 820],
  ["Jordan 1 Retro Low OG SP Travis Scott Black Phantom", "DM7866-001", "Black/White", "j", 3, "2022-12-16", 690],
  ["Jordan 1 Retro Low OG SP Travis Scott Velvet Brown", "DM7866-202", "Velvet Brown/Sail", "j", 4, "2024-12-12", 560],
  ["Jordan 1 Retro Low OG SP Travis Scott Medium Olive (Women's)", "DZ4137-106", "Sail/Medium Olive", "w", 3, "2023-10-25", 520],
  ["Jordan 1 Retro Low OG SP Travis Scott Canary (Women's)", "DZ4137-700", "Canary/Sail", "w", 3, "2024-06-08", 480],
  ["Jordan 1 Retro Low OG SP Travis Scott Shy Pink (Women's)", "DZ4137-601", "Shy Pink/Sail", "w", 4, "2025-07-26", 520],
  ["Jordan 1 Retro Low OG SP Travis Scott Fragment", "DM7866-140", "Sail/Military Blue", "j", 2, "2021-08-13", 1350],
  ["Jordan 1 Retro Low OG Black Toe", "CZ0790-106", "White/Black/Varsity Red", "j", 3, "2023-02-08"],
  ["Jordan 1 Retro Low OG Chicago", "CZ0790-160", "White/Varsity Red/Black", "j", 3, "2025-04-12"],
  ["Jordan 1 Retro Low OG UNC Powder Blue", "CZ0790-104", "White/Dark Powder Blue", "j", 2, "2022-08-06"],
  ["Jordan 1 Retro Low OG Mocha", "CZ0790-102", "White/Dark Mocha", "j", 2, "2024-07-13"],
  ["Jordan 1 Retro Low OG Year of the Snake", "HF3138-100", "Sail/Gym Red", "j", 2, "2025-01-25"],
  ["Jordan 1 Retro Low OG Starfish", "CZ0790-801", "Starfish/Black", "j", 2, "2024-03-09"],
  ["Jordan 1 Retro Low OG Bred Toe (Women's)", "CZ0775-612", "Gym Red/Black/White", "w", 2, "2025-08-23"],
  ["Jordan 1 Retro Low OG Chicago (GS)", "CZ0858-160", "White/Varsity Red/Black", "gs", 2, "2025-04-12"],
  ["Jordan 1 Retro Low OG Black Toe (GS)", "CZ0858-106", "White/Black/Varsity Red", "gs", 2, "2023-02-08"],
  // Jordan 3
  ["Jordan 3 Retro White Cement Reimagined", "DN3707-100", "Summit White/Fire Red", "j", 3, "2023-03-11"],
  ["Jordan 3 Retro Black Cement (2018)", "854262-001", "Black/Cement Grey", "j", 2, "2018-02-17"],
  ["Jordan 3 Retro Fire Red (2022)", "DN3707-160", "White/Fire Red", "j", 2, "2022-09-10"],
  ["Jordan 3 Retro Palomino", "CT8532-102", "Palomino/Black", "j", 2, "2023-01-21"],
  ["Jordan 3 Retro Midnight Navy", "CT8532-140", "White/Midnight Navy", "j", 2, "2022-06-25"],
  ["Jordan 3 Retro Black Cat", "CT8532-001", "Black/Dark Charcoal", "j", 4, "2025-01-04"],
  ["Jordan 3 Retro Green Glow", "CT8532-031", "Wolf Grey/Green Glow", "j", 2, "2024-07-13"],
  ["Jordan 3 Retro Cement Grey", "CT8532-012", "Cement Grey/Fire Red", "j", 2, "2024-05-11"],
  ["Jordan 3 Retro Pure Money", "CT8532-111", "White/Metallic Silver", "j", 3, "2025-08-02"],
  ["Jordan 3 Retro Wizards", "CT8532-148", "White/Metallic Copper/Navy", "j", 2, "2026-02-14"],
  ["Jordan 3 Retro Lucky Green (Women's)", "CK9246-136", "White/Lucky Green", "w", 2, "2023-04-08"],
  ["Jordan 3 Retro J Balvin Medellin Sunset", "FN0344-901", "Multi-Color", "j", 2, "2023-09-21", 330],
  ["Jordan 3 Retro Black Cat (GS)", "DM0967-001", "Black/Dark Charcoal", "gs", 3, "2025-01-04"],
  // Jordan 4
  ["Jordan 4 Retro Bred Reimagined", "FV5029-006", "Black/Fire Red", "j", 5, "2024-02-17"],
  ["Jordan 4 Retro Bred Reimagined (GS)", "FQ8213-006", "Black/Fire Red", "gs", 4, "2024-02-17"],
  ["Jordan 4 Retro Military Black", "DH6927-111", "White/Black", "j", 4, "2022-05-21"],
  ["Jordan 4 Retro Military Black (GS)", "408452-111", "White/Black", "gs", 3, "2022-05-21"],
  ["Jordan 4 Retro Military Blue (2024)", "FV5029-141", "Off White/Military Blue", "j", 4, "2024-05-04"],
  ["Jordan 4 Retro Red Cement", "DH6927-161", "White/Fire Red", "j", 3, "2023-09-09"],
  ["Jordan 4 Retro Thunder (2023)", "DH6927-017", "Black/Tour Yellow", "j", 3, "2023-05-13"],
  ["Jordan 4 Retro Midnight Navy", "DH6927-140", "White/Midnight Navy", "j", 3, "2022-10-29"],
  ["Jordan 4 Retro Black Cat (2020)", "CU1110-010", "Black", "j", 3, "2020-01-22", 420],
  ["Jordan 4 Retro White Oreo (2021)", "CT8527-100", "White/Tech Grey", "j", 2, "2021-07-03"],
  ["Jordan 4 Retro SB Pine Green", "DR5415-103", "Sail/Pine Green", "j", 3, "2023-03-21", 330],
  ["Jordan 4 Retro SB Navy", "DR5415-100", "White/Navy", "j", 4, "2025-03-22", 290],
  ["Jordan 4 Retro Black Canvas", "DH7138-006", "Black/Light Steel Grey", "j", 2, "2022-10-01"],
  ["Jordan 4 Retro Bred (2019)", "308497-060", "Black/Cement Grey", "j", 2, "2019-05-04"],
  ["Jordan 4 Retro Fire Red (2020)", "DC7770-160", "White/Fire Red", "j", 2, "2020-11-28"],
  ["Jordan 4 Retro Infrared", "DH6927-061", "Black/Infrared", "j", 2, "2022-06-11"],
  ["Jordan 4 Retro University Blue", "CT8527-400", "University Blue/Tech Grey", "j", 2, "2021-04-28"],
  ["Jordan 4 Retro Fear (2024)", "FQ8138-002", "Black/Cool Grey", "j", 3, "2024-08-03"],
  ["Jordan 4 Retro Oxidized Green", "FQ8138-103", "White/Oxidized Green", "j", 3, "2024-06-08"],
  ["Jordan 4 Retro Wet Cement", "FQ7928-001", "Cement Grey/Black", "j", 2, "2024-07-27"],
  ["Jordan 4 Retro White Cement (2025)", "FV5029-100", "White/Cement Grey", "j", 5, "2025-06-14"],
  ["Jordan 4 Retro Rare Air", "FV5029-103", "White/Fire Red/Black", "j", 3, "2025-04-26"],
  ["Jordan 4 Retro White Thunder", "FQ8138-101", "White/Tour Yellow", "j", 3, "2025-05-24"],
  ["Jordan 4 Retro Toro Bravo", "FQ8138-600", "Fire Red/Black", "j", 4, "2025-11-22"],
  ["Jordan 4 Retro Black Cat (2025)", "FV5029-010", "Black/Light Graphite", "j", 5, "2025-11-28"],
  ["Jordan 4 Retro Lakers", "FV5029-500", "Court Purple/Varsity Maize", "j", 3, "2026-04-04"],
  ["Jordan 4 Retro Cool Grey (2026)", "FV5029-004", "Cool Grey/Pure Silver", "j", 4, "2026-07-18"],
  ["Jordan 4 Retro Nigel Sylvester Brick by Brick", "HF4340-800", "Sail/Brick Red", "j", 2, "2024-11-14", 340],
  ["Jordan 4 Retro Union Off Noir", "DC9533-001", "Off Noir/Black", "j", 1, "2020-11-28", 460],
  ["Jordan 4 Retro Red Thunder", "CT8527-016", "Black/Crimson", "j", 2, "2022-01-15"],
  ["Jordan 4 Retro Lightning (2021)", "CT8527-700", "Tour Yellow/Dark Blue Grey", "j", 2, "2021-08-28"],
  ["Jordan 4 Retro Military Blue (2024) (GS)", "FQ8213-141", "Off White/Military Blue", "gs", 3, "2024-05-04"],
  ["Jordan 4 Retro Shimmer (Women's)", "DJ0675-200", "Shimmer/Bronze Eclipse", "w", 1, "2021-09-11"],
  ["Jordan 4 Retro Frozen Moments (Women's)", "AQ9129-001", "Light Iron Ore", "w", 2, "2023-06-03"],
  ["Jordan 4 Retro Vivid Sulfur (Women's)", "AQ9129-101", "Sail/Vivid Sulfur", "w", 2, "2024-03-02"],
  ["Jordan 4 Retro Seafoam (Women's)", "AQ9129-103", "Sail/Seafoam", "w", 2, "2023-03-25"],
  ["Jordan 4 Retro Abundance (Women's)", "AQ9129-102", "Sail/Light Iron Ore", "w", 2, "2025-03-08"],
  ["Jordan 4 Retro White Cement (GS)", "FQ8213-100", "White/Cement Grey", "gs", 4, "2025-06-14"],
  ["Jordan 4 Retro Black Cat (2025) (GS)", "FQ8213-010", "Black/Light Graphite", "gs", 4, "2025-11-28"],
  // Jordan 5, 6, 11, 12
  ["Jordan 5 Retro Aqua", "DD0587-047", "Black/Aquatone", "j", 2, "2021-12-04"],
  ["Jordan 5 Retro Black Metallic Reimagined", "HF3975-001", "Black/Metallic Silver", "j", 3, "2025-02-01"],
  ["Jordan 5 Retro Racer Blue", "CT4838-004", "Black/Racer Blue", "j", 2, "2021-04-10"],
  ["Jordan 5 Retro Olive (2024)", "DD0587-308", "Army Olive/Solar Orange", "j", 2, "2024-03-30"],
  ["Jordan 5 Retro Grape (2025)", "HQ7978-100", "White/Grape Ice", "j", 4, "2025-10-25"],
  ["Jordan 5 Retro Off-White Sail", "DH8565-100", "Sail/Fire Red", "j", 1, "2021-12-03", 390],
  ["Jordan 5 Retro Grape (2025) (GS)", "HQ7979-100", "White/Grape Ice", "gs", 3, "2025-10-25"],
  ["Jordan 6 Retro Toro Bravo", "CT8529-600", "University Red/Black", "j", 2, "2023-02-25"],
  ["Jordan 6 Retro Infrared (2019)", "384664-060", "Black/Infrared", "j", 2, "2019-02-16"],
  ["Jordan 6 Retro White Infrared (2024)", "CT8529-106", "White/Infrared", "j", 3, "2024-12-07"],
  ["Jordan 6 Retro Travis Scott British Khaki", "DH0690-200", "British Khaki/Bright Crimson", "j", 2, "2021-04-30", 420],
  ["Jordan 6 Retro White Infrared (2024) (GS)", "384665-106", "White/Infrared", "gs", 2, "2024-12-07"],
  ["Jordan 11 Retro Cherry (2022)", "CT8012-116", "White/Varsity Red", "j", 3, "2022-12-10"],
  ["Jordan 11 Retro DMP Gratitude (2023)", "CT8012-170", "White/Metallic Gold", "j", 3, "2023-12-09"],
  ["Jordan 11 Retro Cool Grey (2021)", "CT8012-005", "Medium Grey/White", "j", 2, "2021-12-11"],
  ["Jordan 11 Retro Legend Blue (2024)", "CT8012-104", "White/Legend Blue", "j", 4, "2024-12-14"],
  ["Jordan 11 Retro Legend Blue (2024) (GS)", "378038-104", "White/Legend Blue", "gs", 3, "2024-12-14"],
  ["Jordan 11 Retro Gamma Blue (2025)", "CT8012-047", "Black/Gamma Blue", "j", 4, "2025-12-13"],
  ["Jordan 11 Retro Bred (2019)", "378037-061", "Black/Varsity Red", "j", 2, "2019-12-14"],
  ["Jordan 11 Retro Space Jam (2016)", "378037-003", "Black/Concord", "j", 1, "2016-12-10"],
  ["Jordan 11 Retro Bred Velvet (Women's)", "DB5457-061", "Black/Varsity Red", "w", 2, "2021-12-11"],
  ["Jordan 11 Retro Low Space Jam (2026)", "FV5104-004", "Black/Concord", "j", 3, "2026-05-23"],
  ["Jordan 11 Retro Cherry (2022) (GS)", "378038-116", "White/Varsity Red", "gs", 2, "2022-12-10"],
  ["Jordan 11 Retro Gamma Blue (2025) (GS)", "378038-047", "Black/Gamma Blue", "gs", 3, "2025-12-13"],
  ["Jordan 12 Retro Cherry (2023)", "CT8013-116", "White/Varsity Red", "j", 2, "2023-10-28"],
  ["Jordan 12 Retro Playoffs (2022)", "CT8013-006", "Black/Varsity Red", "j", 2, "2022-04-02"],
  ["Jordan 12 Retro Flu Game (2025)", "CT8013-002", "Black/Varsity Red", "j", 3, "2025-05-31"],
  ["Jordan 12 Retro Taxi Flip", "CT8013-071", "Black/Taxi", "j", 2, "2026-01-31"],
  ["Jordan 12 Retro Flu Game (2025) (GS)", "153265-002", "Black/Varsity Red", "gs", 2, "2025-05-31"],
  // Nike Dunk Low
  ["Nike Dunk Low Retro White Black Panda", "DD1391-100", "White/Black", "m", 5, "2021-03-10"],
  ["Nike Dunk Low Retro White Black Panda (Women's)", "DD1503-101", "White/Black", "w", 4, "2021-03-10"],
  ["Nike Dunk Low Retro White Black Panda (GS)", "CW1590-100", "White/Black", "gs", 4, "2021-03-10"],
  ["Nike Dunk Low Grey Fog", "DD1391-103", "White/Grey Fog", "m", 3, "2021-08-10"],
  ["Nike Dunk Low UNC (2021)", "DD1391-102", "White/University Blue", "m", 2, "2021-06-24"],
  ["Nike Dunk Low Championship Red", "DD1391-600", "White/University Red", "m", 2, "2021-04-01"],
  ["Nike Dunk Low Michigan", "DD1391-700", "Varsity Maize/Midnight Navy", "m", 2, "2021-10-21"],
  ["Nike Dunk Low Two-Toned Grey", "DJ6188-001", "Light Smoke Grey/White", "m", 2, "2022-06-30"],
  ["Nike Dunk Low Reverse Panda", "DJ6188-002", "Black/White", "m", 3, "2022-08-18"],
  ["Nike Dunk Low Vintage Green", "DQ8580-100", "White/Shadow Green", "m", 2, "2022-10-15"],
  ["Nike Dunk Low Chicago Split", "DZ2536-600", "University Red/Black", "m", 2, "2022-12-08"],
  ["Nike Dunk Low Retro Grey Black", "DJ6188-003", "Wolf Grey/Black", "m", 3, "2025-01-16"],
  ["Nike Dunk Low Retro Valerian Blue", "DD1391-401", "White/Valerian Blue", "m", 3, "2025-04-03"],
  ["Nike Dunk Low Retro Cacao Wow", "DD1391-210", "Sail/Cacao Wow", "m", 3, "2025-08-14"],
  ["Nike Dunk Low Retro Burgundy Crush", "DD1391-602", "White/Team Red", "m", 3, "2025-11-06"],
  ["Nike Dunk Low Retro Mineral Teal", "DD1391-301", "White/Mineral Teal", "m", 2, "2026-03-12"],
  ["Nike Dunk Low Retro Olive Panda", "DD1391-302", "Sail/Medium Olive", "m", 4, "2026-05-07"],
  ["Nike Dunk Low Medium Curry", "DD1390-100", "Sail/Fossil", "m", 2, "2021-06-24"],
  ["Nike Dunk Low Coast (Women's)", "DD1503-100", "White/Coast", "w", 2, "2021-05-20"],
  ["Nike Dunk Low Rose Whisper (Women's)", "DD1503-118", "White/Rose Whisper", "w", 2, "2021-09-09"],
  ["Nike Dunk Low Cacao Wow (Women's)", "DD1503-124", "Sail/Cacao Wow", "w", 3, "2025-08-14"],
  ["Nike Dunk Low Next Nature Pale Coral (Women's)", "DD1873-100", "White/Pale Coral", "w", 2, "2022-03-17"],
  ["Nike Dunk Low Pink Foam (Women's)", "DD1503-602", "Pink Foam/White", "w", 3, "2025-02-20"],
  ["Nike Dunk Low Photon Dust (Women's)", "DD1503-103", "White/Photon Dust", "w", 3, "2021-08-19"],
  ["Nike Dunk Low Light Bone Gum (Women's)", "DD1503-200", "Light Bone/Gum Light Brown", "w", 2, "2026-01-22"],
  ["Nike Dunk Low Grey Fog (GS)", "DH9765-001", "White/Grey Fog", "gs", 3, "2021-08-10"],
  ["Nike Dunk Low Two-Toned Grey (GS)", "DH9765-002", "Light Smoke Grey/White", "gs", 2, "2022-06-30"],
  ["Nike Dunk Low Reverse Panda (GS)", "FD1232-002", "Black/White", "gs", 3, "2022-08-18"],
  // Nike SB Dunk
  ["Nike SB Dunk Low Travis Scott", "CT5053-001", "Multi-Color/Black", "m", 2, "2020-02-29", 1050],
  ["Nike SB Dunk Low Chicago", "BQ6817-600", "Varsity Red/White", "m", 2, "2020-02-01", 260],
  ["Nike SB Dunk Low Court Purple", "BQ6817-500", "Court Purple/Black", "m", 2, "2021-03-04", 260],
  ["Nike SB Dunk Low Jarritos", "FD0860-001", "Phantom/Safety Orange", "m", 3, "2023-04-20", 310],
  ["Nike SB Dunk Low Street Hawker", "CV1628-800", "Habanero Red/Black", "m", 1, "2021-02-05", 520],
  ["Nike SB Dunk Low Big Money Savings", "FZ3129-200", "Gum Light Brown/Black", "m", 2, "2023-07-01", 220],
  ["Nike SB Dunk Low Why So Sad?", "DX5549-400", "Coast/Black", "m", 2, "2023-07-15", 240],
  ["Nike SB Dunk Low Futura Bleached Aqua", "HF6061-400", "Bleached Aqua/White", "m", 2, "2024-10-26", 210],
  ["Nike SB Dunk Low Concepts Orange Lobster", "FD8776-800", "Orange Frost/White", "m", 2, "2022-12-17", 340],
  ["Nike SB Dunk Low Tightbooth", "FD2629-100", "Summit White/Black", "m", 2, "2024-03-01", 230],
  ["Nike SB Dunk Low Pro Grey Gum", "BQ6817-007", "Iron Grey/Gum Light Brown", "m", 2, "2025-03-15", 150],
  ["Nike SB Dunk Low Pro Black Gum", "BQ6817-010", "Black/Gum Light Brown", "m", 3, "2025-06-07", 150],
  ["Nike SB Dunk Low Verdy Visty", "HF3704-100", "White/Lucky Green", "m", 3, "2025-08-30", 280],
  ["Nike SB Dunk Low Coconut Milk", "BQ6817-102", "Coconut Milk/Light Bone", "m", 3, "2026-04-18", 160],
  // Nike Dunk High
  ["Nike Dunk High Retro White Black Panda", "DD1399-105", "White/Black", "m", 3, "2021-06-24"],
  ["Nike Dunk High Retro University Blue", "DD1399-102", "White/University Blue", "m", 2, "2021-12-02"],
  ["Nike Dunk High White Black (Women's)", "DD1869-103", "White/Black", "w", 2, "2021-05-12"],
  ["Nike Dunk High Retro Wolf Grey", "DD1399-101", "White/Wolf Grey", "m", 2, "2025-09-25"],
  // Nike Air Force 1
  ["Nike Air Force 1 Low '07 White", "CW2288-111", "White", "m", 3, "2020-01-01", 110],
  ["Nike Air Force 1 Low '07 Black", "CW2288-001", "Black", "m", 2, "2020-01-01", 110],
  ["Nike Air Force 1 Low '07 White (Women's)", "DD8959-100", "White", "w", 2, "2021-01-01", 105],
  ["Nike Air Force 1 Low White (GS)", "DH2920-111", "White", "gs", 2, "2021-01-01", 90],
  ["Nike Air Force 1 Low Supreme White", "CU9225-100", "White", "m", 2, "2020-03-05", 160],
  ["Nike Air Force 1 Low Supreme Black", "CU9225-001", "Black", "m", 2, "2020-03-05", 160],
  ["Nike Air Force 1 Low Tiffany & Co. 1837", "DZ1382-001", "Black/Multi-Color", "m", 1, "2023-03-07", 520],
  ["Nike Air Force 1 Low '07 LV8 Sail Gum", "DO9784-100", "Sail/Gum Light Brown", "m", 2, "2025-04-17", 130],
  // Nike Air Max
  ["Nike Air Max 1 '86 OG Big Bubble Sport Red", "DQ3989-100", "White/Sport Red", "m", 2, "2023-03-26"],
  ["Nike Air Max 1 '86 OG Big Bubble Royal", "DQ3989-101", "White/Game Royal", "m", 2, "2024-03-26"],
  ["Nike Air Max 1 Patta Waves Monarch", "DH1348-001", "Monarch/Off Noir", "m", 1, "2021-10-08", 330],
  ["Nike Air Max 1 Anniversary Red", "908375-103", "White/University Red", "m", 2, "2017-03-26"],
  ["Nike Air Max 1 '86 OG Obsidian", "HF2903-100", "White/Obsidian", "m", 3, "2025-03-26"],
  ["Nike Air Max 90 Infrared (2020)", "CT1685-100", "White/Radiant Red", "m", 2, "2020-03-26"],
  ["Nike Air Max 90 Triple White", "CN8490-100", "White", "m", 2, "2020-01-01", 120],
  ["Nike Air Max 90 Black White", "CN8490-002", "Black/White", "m", 2, "2020-01-01", 130],
  ["Nike Air Max 90 Off-White Desert Ore", "AA7293-200", "Desert Ore/Hyper Jade", "m", 1, "2019-02-07", 420],
  ["Nike Air Max 90 Bacon (2021)", "CU1816-100", "Sail/Hyper Pink", "m", 2, "2021-03-26"],
  ["Nike Air Max 95 OG Neon (2020)", "CT1689-001", "Black/Volt", "m", 2, "2020-03-26"],
  ["Nike Air Max 95 Triple Black", "609048-092", "Black", "m", 2, "2020-01-01", 170],
  ["Nike Air Max 95 Corteiz Gutta Green", "FB2709-002", "Gutta Green/Black", "m", 2, "2023-11-11", 330],
  ["Nike Air Max 95 Corteiz Aegean Storm", "FB2709-001", "Aegean Storm/Sequoia", "m", 3, "2023-07-15", 360],
  ["Nike Air Max 95 OG Big Bubble Neon", "HM4740-001", "Black/Volt", "m", 3, "2025-03-26"],
  ["Nike Air Max Plus Triple Black", "604133-050", "Black", "m", 2, "2020-01-01", 175],
  ["Nike Air Max Plus Triple White", "604133-139", "White", "m", 2, "2020-01-01", 175],
  ["Nike Air Max Plus OG Voltage Purple", "DX0755-500", "Voltage Purple/Black", "m", 2, "2025-05-15"],
  ["Nike Air Max Plus Sunset", "HF0552-001", "Black/Bright Ceramic", "m", 3, "2025-08-07"],
  ["Nike Air Max Dn All Night", "DV3337-008", "Black/Light Smoke Grey", "m", 2, "2024-03-26"],
  ["Nike Air Max Dn8 Black Volt", "FQ7860-001", "Black/Volt", "m", 2, "2025-03-26"],
  // Nike running and the rest
  ["Nike Zoom Vomero 5 Photon Dust Metallic Silver", "FB9149-101", "Photon Dust/Metallic Silver", "m", 4, "2024-11-21"],
  ["Nike Zoom Vomero 5 Cobblestone", "FB9149-100", "Cobblestone/Flat Pewter", "m", 3, "2025-02-27"],
  ["Nike Zoom Vomero 5 Black Anthracite", "HF1553-001", "Black/Anthracite", "m", 3, "2025-06-19"],
  ["Nike Zoom Vomero 5 Supersonic (Women's)", "FB8825-001", "Photon Dust/Supersonic", "w", 3, "2025-04-10"],
  ["Nike Zoom Vomero 5 Light Orewood Brown (Women's)", "FB8825-100", "Light Orewood Brown/Sail", "w", 2, "2025-09-04"],
  ["Nike Mind 001 Black", "HQ4307-001", "Black/Hyper Crimson", "sl", 3, "2026-01-15", 130],
  ["Nike Mind 001 Light Bone", "HQ4307-002", "Light Bone/Hyper Crimson", "sl", 3, "2026-02-12", 130],
  ["Nike Mind 002 Black", "HQ4308-001", "Black/Hyper Crimson", "m", 3, "2026-02-12", 170],
  ["Nike Calm Slide Black", "FD4116-001", "Black", "sl", 3, "2023-04-20", 65],
  ["Nike Calm Slide Sail", "FD4116-100", "Sail", "sl", 2, "2023-04-20", 65],
  ["Nike Kobe 6 Protro Grinch (2020)", "CW2190-300", "Green Apple/Volt", "m", 3, "2020-12-24", 520],
  ["Nike Kobe 6 Protro Reverse Grinch", "FV4921-600", "Bright Crimson/Black", "m", 3, "2023-12-15", 360],
  ["Nike Kobe 8 Protro Halo", "FJ9364-100", "White", "m", 2, "2024-04-13", 260],
  ["Nike Kobe 8 Protro Radiant Emerald", "HF9550-300", "Radiant Emerald/White", "m", 2, "2024-08-23", 240],
  ["Nike Kobe 5 Protro X8 Chaos", "HQ1149-600", "University Red/White", "m", 3, "2025-08-23", 280],
  ["Nike Shox TL Black", "AR3566-002", "Black/Max Orange", "m", 2, "2024-01-01", 170],
  ["Nike Shox TL Metallic Silver", "AR3566-003", "Metallic Silver/Black", "m", 2, "2025-03-06", 170],
  ["Nike Total 90 III White Black", "FD3612-100", "White/Black", "m", 2, "2025-05-01", 120],
  // New Balance
  ["New Balance 550 White Green", "BB550WT1", "White/Green", "nb", 3, "2020-11-13"],
  ["New Balance 550 White Grey", "BB550PB1", "White/Grey", "nb", 2, "2021-03-01"],
  ["New Balance 550 White Navy", "BB550WCA", "White/Navy", "nb", 2, "2022-04-01"],
  ["New Balance 550 Sea Salt Burgundy", "BB550VTB", "Sea Salt/Burgundy", "nb", 2, "2025-02-01"],
  ["New Balance 550 White Green (GS)", "GSB550WT", "White/Green", "gs", 2, "2021-03-01", 95],
  ["New Balance 550 Aime Leon Dore Natural Green", "BB550ALD", "White/Natural Green", "nb", 1, "2020-10-23", 260],
  ["New Balance 530 White Silver Navy", "MR530SG", "White/Silver", "nb", 3, "2021-06-01", 110],
  ["New Balance 530 Steel Grey", "MR530KA", "Steel Grey/Silver", "nb", 2, "2024-04-01", 110],
  ["New Balance 530 White Silver Navy (GS)", "GR530SB1", "White/Silver", "gs", 2, "2022-03-01", 85],
  ["New Balance 990v6 Made in USA Grey", "M990GL6", "Grey", "nb", 2, "2022-04-22", 230],
  ["New Balance 990v6 Made in USA Black", "M990BK6", "Black", "nb", 2, "2022-08-12", 230],
  ["New Balance 990v4 Made in USA Grey", "U990GR4", "Grey", "nb", 2, "2024-05-09", 230],
  ["New Balance 990v3 Made in USA Grey", "M990GY3", "Grey", "nb", 2, "2023-05-01", 220],
  ["New Balance 990v6 Made in USA Grey Day (2025)", "U990GD6", "Rain Cloud/Silver", "nb", 3, "2025-05-09", 240],
  ["New Balance 2002R Protection Pack Rain Cloud", "M2002RDA", "Rain Cloud", "nb", 3, "2021-07-23"],
  ["New Balance 2002R Protection Pack Phantom", "M2002RDB", "Phantom", "nb", 2, "2021-07-23"],
  ["New Balance 2002R Protection Pack Sea Salt", "M2002RDC", "Sea Salt", "nb", 2, "2021-07-23"],
  ["New Balance 2002R Grey Silver", "ML2002R0", "Grey/Silver", "nb", 2, "2022-03-01"],
  ["New Balance 9060 Rain Cloud Grey", "U9060GRY", "Rain Cloud", "nb", 3, "2022-08-01"],
  ["New Balance 9060 Sea Salt Silver", "U9060WHT", "Sea Salt/Silver", "nb", 3, "2023-02-01"],
  ["New Balance 9060 Black Castlerock", "U9060BLK", "Black/Castlerock", "nb", 3, "2023-01-01"],
  ["New Balance 9060 Mushroom", "U9060MUS", "Mushroom/Brown", "nb", 2, "2024-02-01"],
  ["New Balance 9060 Quartz Grey", "U9060FNB", "Quartz Grey/Silver", "nb", 3, "2025-03-01"],
  ["New Balance 9060 Triple Black", "U9060NRJ", "Black", "nb", 4, "2025-09-01"],
  ["New Balance 9060 Rain Cloud Grey (GS)", "GC9060GY", "Rain Cloud", "gs", 2, "2023-01-01", 120],
  ["New Balance 1906R Silver Metallic", "M1906REU", "Silver Metallic/Sea Salt", "nb", 3, "2023-06-01"],
  ["New Balance 1906R Black", "M1906RCH", "Black/Castlerock", "nb", 3, "2024-01-01"],
  ["New Balance 1906R White Gold", "M1906RCA", "White/Gold", "nb", 2, "2025-04-01"],
  ["New Balance 1906L Black", "U1906LBK", "Black", "nb", 3, "2025-08-01"],
  ["New Balance 1000 Silver Metallic", "M1000SL", "Silver Metallic/Sea Salt", "nb", 3, "2024-10-01"],
  ["New Balance 1000 Black", "M1000BK", "Black/Magnet", "nb", 2, "2025-05-01"],
  ["New Balance 204L Mushroom", "U204LMMC", "Mushroom/Arid Stone", "nb", 3, "2025-03-01"],
  ["New Balance 204L Black", "U204LBK", "Black/Castlerock", "nb", 2, "2025-07-01"],
  ["New Balance 740 Silver Metallic", "U740SR2", "Silver Metallic/White", "nb", 2, "2026-02-01"],
  // adidas
  ["adidas Samba OG Cloud White Core Black", "B75806", "Cloud White/Core Black", "ad", 5, "2018-01-01"],
  ["adidas Samba OG Core Black Gum", "B75807", "Core Black/Gum", "ad", 3, "2018-01-01"],
  ["adidas Samba OG Collegiate Green", "IG6175", "Cloud White/Collegiate Green", "ad", 2, "2024-02-01"],
  ["adidas Samba OG Wonder White Gum", "IE3437", "Wonder White/Gum", "ad", 3, "2024-07-01"],
  ["adidas Samba OG Silver Metallic", "JI2724", "Silver Metallic/Core Black", "ad", 3, "2025-02-01"],
  ["adidas Samba OG Maroon", "JI1350", "Maroon/Cloud White", "ad", 3, "2025-09-01"],
  ["adidas Samba OG Wales Bonner Cream White", "GY5752", "Cream White/Core Black", "ad", 1, "2022-08-01", 280],
  ["adidas Samba Jane White Black (Women's)", "IE1144", "Cloud White/Core Black", "w", 2, "2025-04-01", 110],
  ["adidas Gazelle Indoor Blue Fusion", "IG4994", "Blue Fusion/Cloud White", "ad", 3, "2024-03-01"],
  ["adidas Gazelle Indoor Scarlet", "IF1808", "Scarlet/Cloud White", "ad", 3, "2024-02-01"],
  ["adidas Gazelle Indoor Collegiate Green", "IG4986", "Collegiate Green/Cloud White", "ad", 2, "2024-06-01"],
  ["adidas Gazelle Indoor Pink Glow", "JI2063", "Pink Glow/Cloud White", "ad", 3, "2025-03-01"],
  ["adidas Gazelle Core Black", "BB5476", "Core Black/Cloud White", "ad", 2, "2018-01-01"],
  ["adidas Campus 00s Core Black", "HQ8708", "Core Black/Cloud White", "ad", 3, "2023-01-01"],
  ["adidas Campus 00s Grey White", "HQ8707", "Grey/Cloud White", "ad", 3, "2023-01-01"],
  ["adidas Campus 00s Dark Green", "H03472", "Dark Green/Cloud White", "ad", 2, "2023-06-01"],
  ["adidas Campus 00s Ambient Sky", "ID2036", "Ambient Sky/Cloud White", "ad", 2, "2025-04-01"],
  ["adidas Handball Spezial Navy Gum", "BD7633", "Collegiate Navy/Gum", "ad", 3, "2018-01-01"],
  ["adidas Handball Spezial Light Blue", "BD7632", "Light Blue/Gum", "ad", 3, "2018-01-01"],
  ["adidas Handball Spezial Scarlet", "IE5894", "Scarlet/Gum", "ad", 2, "2024-04-01"],
  ["adidas Handball Spezial Aluminium Core Black", "IF7086", "Aluminium/Core Black", "ad", 3, "2025-01-01"],
  ["adidas SL 72 OG Core Black", "IH7911", "Core Black/Cloud White", "ad", 3, "2025-03-01"],
  ["adidas SL 72 OG Maroon", "JH6436", "Maroon/Cloud White", "ad", 2, "2025-08-01"],
  ["adidas Taekwondo Lace Core Black (Women's)", "JH9643", "Core Black/Cloud White", "w", 3, "2025-05-01", 120],
  ["adidas Tokyo Cream White", "JI0182", "Cream White/Core Black", "ad", 2, "2026-03-01"],
  // ASICS and Onitsuka Tiger
  ["ASICS Gel-1130 White Pure Silver", "1201A256-113", "White/Pure Silver", "as", 3, "2023-03-01"],
  ["ASICS Gel-1130 Black Pure Silver", "1201A256-004", "Black/Pure Silver", "as", 2, "2023-03-01"],
  ["ASICS Gel-1130 Cream Clay Canyon", "1201A255-251", "Cream/Clay Canyon", "as", 2, "2024-05-01"],
  ["ASICS Gel-1130 White Midnight", "1201A256-120", "White/Midnight", "as", 3, "2025-04-01"],
  ["ASICS Gel-Kayano 14 Cream Black", "1201A019-108", "Cream/Black", "as", 3, "2023-02-01"],
  ["ASICS Gel-Kayano 14 White Midnight", "1201A019-107", "White/Midnight", "as", 3, "2023-04-01"],
  ["ASICS Gel-Kayano 14 Silver Black", "1201A019-020", "Pure Silver/Black", "as", 3, "2025-02-01"],
  ["ASICS Gel-Kayano 14 Birch Dark Pewter", "1203A537-200", "Birch/Dark Pewter", "as", 2, "2025-09-01"],
  ["ASICS Gel-1130 White Pink (Women's)", "1202A164-114", "White/Pink", "w", 2, "2025-03-01", 120],
  ["ASICS Gel-NYC Graphite Grey Black", "1201A789-020", "Graphite Grey/Black", "as", 3, "2023-01-01"],
  ["ASICS Gel-NYC Cream Oyster Grey", "1201A789-750", "Cream/Oyster Grey", "as", 2, "2024-03-01"],
  ["ASICS Gel-NYC White Steel Grey", "1203A383-101", "White/Steel Grey", "as", 2, "2025-06-01"],
  ["ASICS GT-2160 White Pure Silver", "1203A320-101", "White/Pure Silver", "as", 2, "2024-06-01"],
  ["ASICS GT-2160 Black Pure Silver", "1203A320-001", "Black/Pure Silver", "as", 2, "2025-10-01"],
  ["Onitsuka Tiger Mexico 66 Yellow Black", "1183C102-751", "Yellow/Black", "as", 3, "2024-01-01", 120],
  ["Onitsuka Tiger Mexico 66 Birch Peacoat", "1183A201-121", "Birch/Peacoat", "as", 2, "2024-01-01", 120],
  ["Onitsuka Tiger Mexico 66 Kill Bill", "1183B510-750", "Yellow/Black", "as", 2, "2025-05-01", 130],
  // Salomon
  ["Salomon XT-6 Black Phantom", "L41086600", "Black/Phantom", "sa", 3, "2022-01-01"],
  ["Salomon XT-6 White Lunar Rock", "L41252900", "White/Lunar Rock", "sa", 2, "2023-03-01"],
  ["Salomon XT-6 Vanilla Ice", "L47445300", "Vanilla Ice/Almond Milk", "sa", 2, "2024-05-01"],
  ["Salomon XT-Whisper Black Silver", "L47592100", "Black/Silver", "sa", 2, "2025-04-01"],
  ["Salomon ACS Pro Black", "L47179800", "Black/Castlerock", "sa", 2, "2024-02-01"],
  ["Salomon Speedcross 3 Black", "L47456700", "Black/Phantom", "sa", 2, "2025-01-01"],
  // Puma
  ["Puma Speedcat OG Red White", "398846-02", "For All Time Red/White", "m", 3, "2025-01-01", 110],
  ["Puma Speedcat OG Black White", "398846-01", "Black/White", "m", 3, "2025-01-01", 110],
];

/* ---------- the models as the demo uses them ---------- */

export type Size = { us: string; eu: string; /** how often this size sells, relative */ w: number; /** Picqer's product code */ code: string };
export type Model = {
  name: string;
  /** the name as it comes through from Alias (GOAT) */
  alias: string;
  style: string;
  color: string;
  run: Run;
  hype: number;
  /** release day (UTC ms) */
  rel: number;
  /** typical resale price in €, for the most asked sizes */
  eur: number;
  shape: Shape;
  sizes: Size[];
  /** what a search looks in (lower case) */
  hay: string;
};

/** How an Alias (GOAT) product name reads once its URL slug is made readable, e.g. "Air Jordan 4 Retro Bred
 * Reimagined", "Dunk Low Retro White Black Panda", "Wmns Air Jordan 4 Retro Frozen Moments", "Adidas Samba Og …"
 * (Nike's own models come without "Nike"). */
export function aliasName(name: string): string {
  let n = name.replace(/^Jordan /, "Air Jordan ").replace(/^Nike /, "").replace(/\s*\(GS\)$/, " GS");
  if (/\(Women's\)$/.test(n)) n = `Wmns ${n.replace(/\s*\(Women's\)$/, "")}`;
  return n.toLowerCase().split(/[^a-z0-9]+/).filter(Boolean).map((w) => (w === "x" ? w : w[0].toUpperCase() + w.slice(1))).join(" ");
}

export function shapeOf(name: string): Shape {
  if (/Slide|Mind 001/.test(name)) return "slide";
  if (/Jordan 1 Retro High|Dunk High/.test(name)) return "high";
  if (/Jordan (3|4|5|6|11|12) Retro(?! Low)/.test(name)) return "mid";
  if (/Air Max|Vomero|Shox|Mind 002|New Balance (990|2002R|9060|1906|530|1000|204L|740)|ASICS (Gel|GT)|Salomon/.test(name)) return "runner";
  return "low";
}

// the usual resale price of a kind (€), before how well the model sells
const PRICE: [RegExp, number][] = [
  [/Jordan 1 Retro High/, 185], [/Jordan 1 Retro Low/, 140], [/Jordan 3 /, 190], [/Jordan 4 /, 225], [/Jordan 5 /, 200], [/Jordan 6 /, 195],
  [/Jordan 11 Retro Low/, 170], [/Jordan 11 /, 225], [/Jordan 12 /, 190], [/SB Dunk/, 170], [/Dunk High/, 130], [/Dunk/, 115], [/Air Force 1/, 110],
  [/Air Max 1 /, 150], [/Air Max 90/, 140], [/Air Max 95/, 180], [/Air Max Plus/, 170], [/Air Max Dn/, 160], [/Vomero/, 155], [/Kobe/, 260],
  [/990v/, 215], [/2002R/, 150], [/9060/, 160], [/1906/, 150], [/550/, 115], [/530/, 100], [/New Balance/, 140],
  [/Samba|Gazelle|Campus|Handball|SL 72|Tokyo/, 105], [/ASICS/, 135], [/Salomon/, 175],
];

const ofKind = (name: string) => PRICE.find(([re]) => re.test(name))?.[1] ?? 140;

/** What one size of a model resells for (€): the model's price, a little more at the ends of the run. */
export function priceOf(m: Model, si: number): number {
  const edge = Math.abs(si - (m.sizes.length - 1) / 2) / Math.max(1, m.sizes.length / 2);
  return Math.round(m.eur * (1 + 0.12 * edge * edge));
}

export const MODELS: Model[] = ROWS.map(([name, style, color, run, hype, rel, eur]) => {
  const r = RUNS[run];
  const kids = run === "gs" ? 0.72 : run === "w" ? 0.92 : 1;
  return {
    name, alias: aliasName(name), style, color, run, hype, rel: Date.parse(`${rel}T00:00:00Z`),
    eur: eur ?? Math.round((ofKind(name) * (0.82 + 0.09 * hype) * kids) / 5) * 5,
    shape: shapeOf(name),
    sizes: r.sizes.map(([us, eu]) => {
      const z = (Number.parseFloat(us) - r.peak) / r.spread;
      // rounded: Math.exp may differ in its last digit between browsers, and every visitor must draw the same rows.
      // Picqer's product code is the style code and the EU size ("DD1391-100-42", "B75806-42 2/3")
      return { us, eu, w: Math.round(Math.exp(-z * z) * 1e6) / 1e6 + 0.06, code: `${style}-${eu}` };
    }),
    hay: `${name}\n${aliasName(name)}\n${style}\n${style.replace(/-/g, " ")}`.toLowerCase(),
  };
});
