// The sales channels of the sneaker demo (Northvale Kicks, lib/demo/clients.ts), in one place. Every channel's data is
// generated by lib/demo/sample.ts. The marketplaces the build started with (CORE_CHANNELS: StockX and Alias, two
// accounts each) have jobs of their own (lib/demo/shape.ts JOBS); the others are slots with the general order and stock
// jobs: to show other platforms (say WooCommerce and eBay for another outreach), change the slot's id, name, logo, role
// and account below, and the ids in the SellPlatform union here and in StoreId (lib/demo/shape.ts); the data, pages and
// tracking follow. Nothing on the page tells the channels apart. No imports, so node --test can load it.

export type SellPlatform = "stockx" | "alias" | "shopify" | "whatnot";
export type Platform = SellPlatform | "picqer";

export type Channel = {
  id: SellPlatform;
  /** shown everywhere (tabs, chips, feed, automations) */
  name: string;
  /** a slug of website data/platforms.json (its logo) */
  logo: string;
  role: string;
  accounts: { id: string; label: string }[];
  /** how often its orders come in (as the automations and connection cards say it) */
  ordersEvery: string;
  ordersMin: number;
  /** the platform sends webhooks: an order reaches Picqer within seconds instead of on the next scheduled run
   * (Shopify does; StockX and Alias don't, so the sync reads them every few minutes) */
  realtime?: boolean;
  syncs: string[];
};

export const CHANNELS: Channel[] = [
  {
    id: "stockx", name: "StockX", logo: "stockx", role: "Marketplace",
    accounts: [{ id: "sx-eu", label: "StockX EU" }, { id: "sx-us", label: "StockX US" }],
    ordersEvery: "every 5 min", ordersMin: 5,
    syncs: ["Sales come in every 5 minutes", "Sold-out sizes pulled every 10 minutes", "Listings checked every 8 minutes"],
  },
  {
    id: "alias", name: "Alias", logo: "alias-goat", role: "Marketplace (GOAT)",
    accounts: [{ id: "al-main", label: "Alias" }, { id: "al-usa", label: "Alias USA" }],
    ordersEvery: "every 7 min", ordersMin: 7,
    syncs: ["Sales come in every 7 minutes", "Last pair sold: pulled from StockX too", "Cancelled orders back into stock"],
  },
  {
    // slot 1: a web store with one shop
    id: "shopify", name: "Shopify", logo: "shopify", role: "Web store",
    accounts: [{ id: "sh-main", label: "Shopify" }],
    ordersEvery: "real time", ordersMin: 0, realtime: true,
    syncs: ["Orders come in the moment they're placed (webhook)", "Stock levels pushed after every sale", "Sold-out sizes hidden in the store"],
  },
  {
    // slot 2: a live-selling marketplace with one account
    id: "whatnot", name: "Whatnot", logo: "whatnot", role: "Live selling",
    accounts: [{ id: "wn-main", label: "Whatnot" }],
    ordersEvery: "every 3 min", ordersMin: 3,
    syncs: ["Show sales come in every 3 minutes", "Only sizes in stock go into a show", "Sold during a show: pulled everywhere"],
  },
];

export const channel = (id: string): Channel | null => CHANNELS.find((c) => c.id === id) ?? null;
/** the marketplaces the build started with (lib/demo/sample.ts: two accounts each, steady sales, their own jobs) */
export const CORE_CHANNELS: readonly SellPlatform[] = ["stockx", "alias"];
export const isCore = (id: string): boolean => (CORE_CHANNELS as readonly string[]).includes(id);
/** the old name of isCore (components/demo/views.tsx still uses it) */
export const fromApi = isCore;
export const PICQER = { name: "Picqer", logo: "picqer" } as const;
